development:
  adapter: postgresql
  database: hw2_development
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: hw2_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: hw2_production
  pool: 5
  timeout: 5000
